# frozen_string_literal: true
# Checking if install_pre_commit_hook.rb exists to avoid requiring in Docker build. This is meant to be run local only
pre_commit_hook_installer = 'scripts/git_hooks/install_pre_commit_hook'
require_relative pre_commit_hook_installer if File.exist?("#{File.dirname(__FILE__)}/#{pre_commit_hook_installer}.rb")
source 'https://rubygems.org'
ruby '2.7.1'
gem 'rake'
gem 'activesupport', '>= 6.1.7.5'
gem 'aws-sdk-applicationautoscaling', '>= 1.49.0'
gem 'aws-sdk-autoscaling', '>= 1.50.0'
gem 'aws-sdk-core', '>= 3.109.3'
gem 'aws-sdk-ec2', '>= 1.210.0'
gem 'aws-sdk-ecr', '>= 1.40.0'
gem 'aws-sdk-elasticloadbalancing', '>= 1.30.0'
gem 'aws-sdk-lambda', '>= 1.53.0'
gem 'aws-sdk-rds', '>= 1.106.0'
gem 'aws-sdk-s3', '>= 1.85.0'
gem 'colorize'
gem 'dogapi'
gem 'faraday_middleware'
gem 'faraday_middleware-aws-sigv4'
gem 'httparty'
gem 'mail'
gem 'net-ssh'
gem 'os'
gem 'parallel'
gem 'redis'
group :test do
  gem 'byebug'
  gem 'git', '>= 1.13.0'
  gem 'octokit', '>= 4.20.0'
  gem 'pry'
  gem 'rubocop', '>= 1.3.1'
  gem 'rubocop-performance', '>= 1.9.0'
  gem 'test-unit'
end
group :local do
  gem 'rdoc', '>= 6.3.1'
end